spring.application.name=lab1-information-security

spring.datasource.url=jdbc:postgresql://localhost:5432/lab_inf_security
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=supersecretkeysupersecretkeysupersecretkey
jwt.expiration-ms=3600000
