name: dependency-check
on:
  push:
  pull_request:
  schedule:
    - cron: "0 3 * * 1"
jobs:
  depcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Run Dependency Check (SCA)
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          mkdir -p ./dependency-check-data
          mvn -B org.owasp:dependency-check-maven:check \
            -Dnvd.apiKey=$NVD_API_KEY \
            -DdataDirectory=./dependency-check-data \
            -Dformat=HTML \
            -DfailBuildOnCVSS=0 \
            -DsuppressionFile=dependency-check-suppressions.xml \
            -Dossindex.skip=true
        continue-on-error: false

      - name: Report of Dependency Check
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html


      - name: OWASP Dependency-Check (docker)
        continue-on-error: true
        run: |
          mkdir -p reports
          docker run --rm \
            -v "${{ github.workspace }}:/src" \
            owasp/dependency-check:latest \
            --project "${{ github.repository }}" \
            --scan /src \
            --format HTML \
            --out /src/reports \
            --failOnCVSS 11 \
            --enableRetired \
            --nvdApiKey "${{ secrets.NVD_API_KEY }}" \
            --ossIndexUsername "${{ secrets.OSSINDEX_USER }}" \
            --ossIndexPassword "${{ secrets.OSSINDEX_TOKEN }}"
          
      - name: OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@1.1.0
        env:
          JAVA_HOME: /opt/jdk
          NVD_API_KEY: ${{ secrets.OSSINDEX_TOKEN }}
          
        with:
          project: ${{ github.repository }}
          path: .
          format: 'HTML'
          args: >-
            --failOnCVSS 7
            --enableRetired
            --disableOssIndex

      - name: Save HTML report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/dependency-check-report.html
