name: dependency-check
on:
  push:
  pull_request:
  schedule:
    - cron: "0 3 * * 1"
jobs:
  depcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@1.1.0
        env:
          JAVA_HOME: /opt/jdk
          OSSINDEX_USER: ${{ secrets.OSSINDEX_USER }}
          OSSINDEX_TOKEN: ${{ secrets.OSSINDEX_TOKEN }}
        with:
          project: ${{ github.repository }}
          path: .
          format: 'HTML'
          args: >-
            --failOnCVSS 7
            --enableRetired

      - name: Save HTML report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/dependency-check-report.html
